[versions]
guava = "32.1.3-jre"
shadow = "8.1.1"
picocli = "4.7.5"
jsoup = "1.17.2"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
